### ISSUE TITLE
Okta provisioning 

### ISSUE THREAD

**Issue by bizonek27** [jaredhendrickson13/pfsense-saml2-auth#2]
Hi

I have tested your software (only tested this will not be used on production env) but if you use Application username format as Custom and user.nickName (example only) you don't have to create any local user.
All works fine based on Remote Groups.

**Comment by jaredhendrickson13** [comment]
Correct. A local user is only needed if the IdP does not return a group attribute in the assertion. Okta does return the group attribute so the mapping works without the need for a local user.
