### ISSUE TITLE
Unable to install on pfSense 23.01

### ISSUE THREAD

**Issue by ilicilho** [jaredhendrickson13/pfsense-saml2-auth#32]
When try to install on pfSense Plus 23.01 I see this error: ld-elf.so.1: /usr/local/sbin/pkg: Undefined symbol "__libc_start1@FBSD_1.7"

**Comment by jaredhendrickson13** [comment]
There are a couple issues here: 

1. pfSense Plus is not currently supported. Supported versions are listed [here](https://github.com/jaredhendrickson13/pfsense-saml2-auth?tab=readme-ov-file#supported-versions). The package may still install, but it will likely break things for pfSense Plus installations. If you do choose to proceed, I would recommend having a suitable backup on hand.
2. The error you are seeing typically occurs when `pkg` is staged for an architecture upgrade on your system (I.e. there's an available pfSense Plus update). You can use `pkg-static` instead to use the version of `pkg` that was initially included with your version of pfSense Plus.
